### ISSUE TITLE
Error No module named subtitles_generator

### ISSUE THREAD

**Issue by msdl2022** [konverner/subtitles-generator#5]
C:\Users\mayco\Downloads\subtitles-generator-main>python main.py large portuguese .\videoyt.mp4
Traceback (most recent call last):
  File "C:\Users\mayco\Downloads\subtitles-generator-main\main.py", line 13, in <module>
    from subtitles_generator.core import Model
ModuleNotFoundError: No module named 'subtitles_generator'

![issue2024-03-30 090157](https://github.com/konverner/subtitles-generator/assets/21229125/810f8d67-2a2c-4edc-ab32-0184428129c3)

**Comment by konverner** [comment]
Hi

Currently, I do not distribute this package via pip. You are supposed to write `pip install .` from the main directory. It is noted here:

https://github.com/konverner/subtitles-generator/blob/main/notebooks/subtitles_generator.ipynb

So, just replace your `pip install subtitles_generator` with `pip install .` . 

I will add this remark to README. Thanks.
